app/main/__init__.py
from flask import Blueprint

main = Blueprint(
    'main', __name__, template_folder='templates', static_folder='static')

from . import views

app/main/case_studies/__init__.py
# Things to be exported for the module!
from .common import studies_summary, study

app/main/views.py
from datetime import datetime, timedelta
import json

from flask import render_template, make_response, current_app, \
    flash, url_for, redirect, jsonify, Response
from flask.ext.login import current_user, login_required

from app.main import main
from app.models import User
from app.helpers import is_native


@main.route("/", methods=["GET"])
def index():
    """Return a friendly HTTP greeting."""

    if current_user.is_authenticated:
        # If authenticated - push into app, not homepage
        if current_user.is_sudo():
            # Staffjoy user. Go to Euler.
            return redirect(url_for("euler.index"))

        admins = current_user.admin_of.all()
        if len(admins) > 0:
            # Go to manage app
            return redirect(
                url_for("manager.manager_app", org_id=admins[0].id))

        memberships = current_user.memberships()
        if len(memberships) > 0:
            # Go to planner
            m = memberships[0]
            return redirect(
                url_for(
                    "myschedules.myschedules_app",
                    org_id=m.get("organization_id"),
                    location_id=m.get("location_id"),
                    role_id=m.get("role_id"),
                    user_id=current_user.id))

        # Nothing left - default to portal
        return redirect(url_for("auth.portal"))

    if is_native():
        return redirect(url_for("auth.native_login"))

    return render_template("homepage.html")


@main.route("/sign-up/", methods=["GET"])
def sign_up():
    """ Lead capture page! """
    if current_user.is_authenticated:
        return redirect(url_for("auth.portal"))

    return redirect(url_for("auth.free_trial"))


@main.route("/bootstrap-demo/", methods=["GET"])
def strap_me():
    """Return a friendly HTTP greeting."""
    flash("This is a general flash")
    flash("This is an informative", "info")
    flash("This is an unhappy flash >.<", "danger")
    flash("but news can also be good :-)", "success")
    return render_template("bootstrap-demo.html")


@main.route("/sitemap.xml", methods=["GET"])
def sitemap():
    """Generate sitemap.xml. Makes a list of urls and date modified."""
    pages = []

    ten_days_ago = datetime.now() - timedelta(days=10)

    # static pages
    for rule in current_app.url_map.iter_rules():
        # TODO - can we filter by blueprint?
        # Right now the argumetn call seems to be fine.
        if "GET" in rule.methods \
                and len(rule.arguments) == 0 \
                and rule.endpoint not in ["main.robots", "main.sitemap", "main.strap_me"] \
                and (
                    rule.endpoint[0:5] == "main."
                    or rule.endpoint == "auth.login"
                ):
            pages.append([rule.rule, ten_days_ago.date().isoformat()])

    sitemap_xml = render_template("main/sitemap.xml", pages=pages)
    response = make_response(sitemap_xml)
    response.headers["Content-Type"] = "application/xml"
    return response


@main.route("/health", methods=["GET"])
def health_check():
    # Run through some basic checks. If any throw an exception, then endpoint will return "unhealthy"
    # Note that unhealthy instances will be terminated
    try:
        # count number of users to ensure that the database is online
        User.query.count()
    except Exception as e:
        current_app.logger.warning("app unhealthy - %s", e)
        return "unhealthy", 500, {'Content-Type': 'text/css; charset=utf-8'}

    return "healthy", 200, {'Content-Type': 'text/css; charset=utf-8'}


@main.route("/robots.txt", methods=["GET"])
def robots():
    template = render_template(current_app.config.get("ROBOTS_TEMPLATE"))
    response = make_response(template)
    response.headers["Content-type"] = "text/plain"
    return response, 200


@main.route("/brand-assets/", methods=["GET"])
def brand_assets():
    return render_template("brand-assets.html")


@login_required
@main.route("/onboarding/employee", methods=["GET"])
def employee_onboarding():
    youtube_video_id = "8Ug3ktbspok"
    return render_template(
        "worker-onboarding-video.html", youtube_video_id=youtube_video_id)


@login_required
@main.route("/onboarding/contractor", methods=["GET"])
def contractor_onboarding():
    youtube_video_id = "7T6AtmxNGcM"
    return render_template(
        "worker-onboarding-video.html", youtube_video_id=youtube_video_id)


@main.route("/mobile-config.json")
def mobile_config():
    """Used by iPhone and Android apps to determine what urls are "native" """
    # Be careful that double escapes work correctly in regex
    payload = json.dumps({
        "hideNavForURLsMatchingPattern":
        '^https?://(suite|dev|stage|www)\\.staffjoy\\.com',
    })
    return Response(response=payload, mimetype="application/json")


@main.route(
    "/api/v1/",
    defaults={"path": ""},
    methods=["GET", "POST", "DELETE", "PATCH"])
@main.route("/api/v1/<path:path>", methods=["GET", "POST", "DELETE", "PATCH"])
def apiv1_deprecate(path):
    return jsonify({
        "message":
        "Version 1 of the Staffjoy API has been deprecated." +
        " Details at help.staffjoy.com"
    }), 410


@main.route("/manage/", defaults={"path": ""})
@main.route("/manage/<path:path>")
def manage_deprecate(path):
    return redirect("/manager/%s" % path)


@main.route("/planner/", defaults={"path": ""})
@main.route("/planner/<path:path>")
def planner_deprecate(path):
    return redirect("/myschedules/%s" % path)

app/main/templates/boss-panels/columns.html
<div class="columns">
    <div class="container">
        <div class="row">
            <div class="col col-md-4 col-xs-12">
                <object data="/static/images/boss-landing/icon-compliance@2x.svg" type="image/svg+xml"></object>
                <h2>Compliance</h2>
                <p>
                    Control how many hours per workday, hours per workweek, and consecutive days each employee works.
                </p>
            </div>
            <div class="col col-md-4 col-xs-12">
                <object data="/static/images/boss-landing/icon-timeclock@2x.svg" type="image/svg+xml"></object>
                <h2>Timeclock</h2>
                <p>
                    Workers can clock in and out of shifts from their mobile device.
                </p>
            </div>
            <div class="col col-md-4 col-xs-12">
                <object data="/static/images/boss-landing/icon-attendance@2x.svg" type="image/svg+xml"></object>
                <h2>Attendance</h2>
                <p>
                    Manage time off requests, easily compare scheduled shifts with hours worked, and export to payroll.
                </p>
            </div>
        </div>
    </div>
</div>

app/main/templates/boss-panels/cta.html
<div class="cta">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 content-parent">
                <div class="content panel panel-primary">
                  <div class="panel-heading">
                      Staffjoy {{plan.name}}
                    </div>
                    <div class="panel-body">
                      <h1 class="price">${{ (plan.unit_price / 100) | int }}<span class="per-month"><span class="per">/</span>MO</span></h1>
                      <p>For up to {{plan.max_workers}} workers</p>
                      <a href="{{ url_for("auth.free_trial", plan="boss-v2") }}" class="sign-up btn btn-primary btn-lg">Start a free trial</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/main/templates/boss-panels/middle.html
<div class="middle">
    <div class="boss-panel save-money">
        <div class="container">
            <div class="row">
                <div class="col-md-3 content-parent center hidden-xs hidden-sm">
                    <object data="/static/images/boss-landing/icon-scheduling@2x.svg" type="image/svg+xml" class="content"></object>
                </div>
                <div class="col-md-9 col-sm-12 content-parent card panel">
                    <div class="content">
                        <object data="/static/images/boss-landing/icon-scheduling@2x.svg" type="image/svg+xml" class="hidden-md hidden-lg"></object>
                        <h2>Save Money with Efficient Scheduling</h2>
                        <p>
                            Over-scheduling costs money. Under-scheduling loses business. Staffjoy matches labor with when your business needs it. Optimize labor - your most expensive resource - with Staffjoy's sophisticated artificial intelligence.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="boss-panel automated-decisions">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-12 content-parent card panel">
                    <div class="content">
                        <object data="/static/images/boss-landing/icon-automate@2x.svg" type="image/svg+xml" class="hidden-md hidden-lg"></object>
                        <h2>Automate Decisions</h2>
                        <p>
                            Compliance is tough. You know the rules - 8 hours per day, 40 hours per week, 6 days in a row - but did you double check that math when you asked somebody to cover an extra shift? You could have just triggered overtime pay without even knowing it! Staffjoy follows your rules to make business-critical decisions quickly.
                        </p>
                    </div>
                </div>
                <div class="col-md-3 content-parent center hidden-xs hidden-sm">
                    <object data="/static/images/boss-landing/icon-automate@2x.svg" type="image/svg+xml" class="content"></object>
                </div>
            </div>
        </div>
    </div>

    <div class="boss-panel happy">
        <div class="container">
            <div class="row">
                <div class="col-md-3 content-parent center hidden-xs hidden-sm">
                    <object data="/static/images/boss-landing/icon-employeeHappy@2x.svg" type="image/svg+xml" class="content"></object>
                </div>
                <div class="col-md-9 col-sm-12 content-parent card panel">
                    <div class="content">
                    <object data="/static/images/boss-landing/icon-employeeHappy@2x.svg" type="image/svg+xml" class="hidden-md hidden-lg"></object>
                        <h2>Make Employees Happy</h2>
                        <p>
                            Don't put a morning person on the closing shift. Engage employees by having them pick the hours they prefer, easily request days off, and claim available shifts from their mobile device. Staffjoy checks that they get enough rest in-between shifts, and it also tries to put people in the times they prefer.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

app/main/templates/boss-panels/overview.html
<div class="boss-panel cta" id="boss-overview">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 content-parent">
                <div class="content">
                    <h1>Automate Employee Scheduling</h1>

                    <p>Save money and make employees happy by having Staffjoy manage your workforce.</p>

                    <a href="{{ url_for("auth.free_trial", plan="boss-v2") }}" class="sign-up btn btn-primary btn-lg">Set up a {{ config.FREE_TRIAL_DAYS }} day trial</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/main/templates/boss.html
{% extends "bootstrap.html" %}

{% block page_id %}boss-landing{% endblock %}

{% block content %}
{% include "boss-panels/overview.html" %}
{% include "boss-panels/middle.html" %}
{% include "boss-panels/columns.html" %}
{% include "boss-panels/cta.html" %}
{% endblock %}

app/main/templates/brand-assets.html
{% extends "bootstrap.html" %}

{% block page_id %}brand-assets{% endblock %}
{% block title %}Brand Assets{% endblock %}
{% block description %}Images, descriptions, and and other assets of the Staffjoy brand.{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <h1 class="page-header">Staffjoy Brand Assets</h1>
            <img src="/static/images/brand-assets/logo/staffjoy.png" alt="Staffjoy logo"/ class="logo">
            <h2>Description</h2>
            <blockquote>
                Staffjoy provides the first workforce tool that builds schedules entirely automatically, while respecting worker preferences and not requiring human scheduler. The web app collects worker availability and business demand, and then schedules workers according to their preferences, as well as the business’s rules. Businesses save money by regaining time spent scheduling, as they utilize the more efficient schedules. 
            </blockquote>

            <h2>Images</h2>
            <table class="table table-bordered brand-assets-table">
                <tr>
                    <th></th>
                    <th class="center">Low-Res</th>
                    <th class="center">High-Res</th>
                    <th class="center">Vector</th>
                </tr>
                <tr>
                    <th>Logo</th>
                    <td class="center"><a href="/static/images/brand-assets/logo/staffjoy.png">PNG<a></td>
                    <td class="center"></td>
                    <td class="center"><a href="/static/images/brand-assets/logo/logo.svg">SVG<a></td>
                </tr>
                <tr>
                    <th>Logo Square</th>
                    <td class="center"><a href="/static/images/brand-assets/logo/square_low.png">PNG<a></td>
                    <td class="center"></td>
                    <td class="center"><a href="/static/images/brand-assets/logo/square.svg">SVG<a></td>
                </tr>
                <tr>
                    <th>Logo Inverse</th>
                    <td class="center"><a href="/static/images/brand-assets/logo/staffjoy_inverse_low.png">PNG<a></td>
                    <td class="center"></td>
                    <td class="center"><a href="/static/images/brand-assets/logo/staffjoy_inverse.svg">SVG<a></td>
                </tr>
                <tr>
                    <th>Logo Square Inverse</th>
                    <td class="center"><a href="/static/images/brand-assets/logo/staffjoy_square_inverse.png">PNG<a></td>
                    <td class="center"></td>
                    <td class="center"><a href="/static/images/brand-assets/logo/staffjoy_square_inverse.svg">SVG<a></td>
                </tr>
                <tr>
                    <th>Philip Thomas, Co-Founder and CEO</a></th>
                    <td class="center"><a href="/static/images/brand-assets/philip/low.jpg">JPG<a></td>
                    <td class="center"><a href="/static/images/brand-assets/philip/high.jpg">JPG<a></td>
                    <td class="center"></td>
                </tr>
                <tr>
                    <th>Philip Thomas, Co-Founder and CEO <span class="text-muted">(square)</span></th>
                    <td class="center"><a href="/static/images/brand-assets/philip/square_low.jpg">JPG<a></td>
                    <td class="center"><a href="/static/images/brand-assets/philip/square_high.jpg">JPG<a></td>
                    <td class="center"></td>
                </tr>
            </table>
        </div>
    </div>
<div>
{% endblock %}

app/main/templates/career_page.html
{% extends "bootstrap.html" %}

{% block page_id %}career{% endblock %}
{% block title %}Open Position: {{name}} - {{location}}{% endblock %}
{% block description %}{{ summary }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <div class="byline">
                <a class="text-muted header-apply btn btn-xs btn-primary pull-right" href="{{config.CAREER_APPLICATION_URL}}" target="_BLANK">Apply For This Job</h5>
                <a href="{{url_for('main.careers')}}"><h5 class="text-muted career-header pull-left">Open Position</h5></a>
            </div>
            {% if hero_image %}
            <img src="{{ hero_image }}" alt="{{name}}" class="hero-image">
            {% endif %}
            <h1 class="page-title">
                {{name}}
            </h1>
            <h5 class="text-muted">{{location}}</h5>

            {{body|safe}}

            <a class="btn btn-block btn-primary btn-apply" href="{{config.CAREER_APPLICATION_URL}}" target="_BLANK">
                Click Here to Apply
            </a>
        </div>
    </div>
<div>
{% endblock %}

app/main/templates/careers_list.html
{% extends "bootstrap.html" %}

{% block page_id %}careers-list{% endblock %}
{% block title %}Careers{% endblock %}
{% block description %}Learn about working at Staffjoy{% endblock %}

{% block content %}
<script>
    $(document).ready(function(){
        $(".career-card").click(function(e) {
            var self = this,
                $target = $(e.target).closest(".career-card"),
                path = $target.attr("data-path")
            ;
            e.preventDefault();
            e.stopPropagation();
            window.location.href = path;
        });
    });
</script>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <h1>Careers</h1>
            {% if careers|length == 0 %}
            <div class="alert alert-info">
                <h4>Check back soon!</h4>
                <p>We currently have no positions available. However, if you are interested in learning more about jobs email <a href="mailto:team@staffjoy.com">team@staffjoy.com</a>.</p>
            </div>
            {% endif %}
            {% for key, data in careers.iteritems() %}
                <div class="panel card career-card" data-path="{{ url_for("main.career_page", slug=key) }}">
                    <div class="panel-heading page-header">
                        <div class="pull-right">
                            <a class="btn btn-primary btn-sm button-align" href="{{ url_for("main.career_page", slug=key) }}">View</a>
                        </div>
                        <h3 class="panel-title location-card-title">
                            {{ data["name"] }}
                        </h3>
                    </div>
                    <div class="panel-body">
                        <p>{{ data["summary"] }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
<div>
{% endblock %}

app/main/templates/case_study.html
{% extends "bootstrap.html" %}

{% block page_id %}case-study{% endblock %}
{% block title %}Case Study: {{ name }}{% endblock %}
{% block description %}{{ summary }}{% endblock %}
{% block head_extra %}{{ header_inject | safe}}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <div class="byline">
                <h5 class="text-muted case-header pull-right date">{{ publication.strftime("%-d %B %Y") }}</h5>
                <a href="{{url_for('main.case_study_list')}}"><h5 class="case-header case-study-head pull-left">Case Study</h5></a>
            </div>
            {% if hero_image %}
            <img src="{{ hero_image }}" alt="{{name}}" class="hero-image">
            {% endif %}
            <h1 class="page-title">{{name}}</h1>

            {{body|safe}}

            <div class="panel panel-info lead-capture-footer">
                <div class="panel-heading">
                    <h3 class="panel-title">Learn More about Staffjoy</h3>
                </div>
                <div class="panel-body">
                    <p>Enter your email to get in contact with our team and keep up with future updates:</p>
                    <form action="//staffjoy.us8.list-manage.com/subscribe/post?u=ec5cd3617447b3dac0483cd29&amp;id=ec1e5e047a" method="post" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
                        <div class="input-group mailchimp-form">
                            <input type="email" value="" name="EMAIL" class="form-control required email" placeholder="email@example.com">
                            <span class="input-group-btn">
                                <input type="submit" value="Submit" name="subscribe" class="btn btn-primary">
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

app/main/templates/case_study_list.html
{% extends "bootstrap.html" %}

{% block page_id %}case-study-list{% endblock %}
{% block title %}Case Studies{% endblock %}
{% block description %}Analysis of how Staffjoy decreases labor costs.{% endblock %}

{% block content %}
<script>
    $(document).ready(function(){
        $(".case-study-card").click(function(e) {
            var self = this,
                $target = $(e.target).closest(".case-study-card"),
                path = $target.attr("data-path")
            ;
            e.preventDefault();
            e.stopPropagation();
            window.location.href = path;
        });
    });
</script>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <h1>Case Studies</h1>
            {% if studies|length == 0 %}
            <div class="alert alert-info">
                <h4>Coming Soon!</h4>
                <p>Our first case study will be published soon. Check out <a href="https://blog.staffjoy.com">Blog.Staffjoy.com</a> for more information about our deployments.</p>
            </div>
            {% endif %}
            {% for key, data in studies.iteritems() %}
                <div class="panel card case-study-card" data-path="{{ url_for("main.case_study", slug=key) }}">
                    <div class="panel-heading page-header">
                        <div class="pull-right">
                            <a class="btn btn-primary btn-sm button-align" href="{{ url_for("main.case_study", slug=key) }}">View</a>
                        </div>
                        <h3 class="panel-title location-card-title">
                            {{ data["short_name"] }}
                        </h3>
                    </div>
                    <div class="panel-body">
                        <p>{{ data["summary"] }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
<div>
{% endblock %}

app/main/templates/flex-panels/columns.html
<div class="columns">
    <div class="container">
        <div class="row">
            <div class="col col-md-4 col-xs-12">
                <object data="/static/images/flex-landing/icon-api@2x.svg" type="image/svg+xml"></object>
                <h2>Open API</h2>
                <p>
                    Access and control all of your data for integrations and apps.
                </p>
            </div>
            <div class="col col-md-4 col-xs-12">
                <object data="/static/images/flex-landing/icon-time-attendance@2x.svg" type="image/svg+xml"></object>
                <h2>Time and Attendance</h2>
                <p>
                    Compare when contractors start work to the schedule for payroll accuracy.
                </p>
            </div>
            <div class="col col-md-4 col-xs-12">
                <object data="/static/images/flex-landing/icon-realtime@2x.svg" type="image/svg+xml"></object>
                <h2>Real-Time</h2>
                <p>
                    Staffjoy automatically alerts contractors about schedule changes.
                </p>
            </div>
        </div>
    </div>
</div>

app/main/templates/flex-panels/cta.html
<div class="cta">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 content-parent">
                <div class="content panel panel-primary">
                  <div class="panel-heading">
                      Staffjoy {{plan.name}}
                    </div>
                    <div class="panel-body">
                      <h1 class="price">${{ (plan.unit_price / 100) | int }}<span class="per-month"><span class="per">/</span>MO</span></h1>
                      <p>For up to {{plan.max_workers}} workers</p>
                      <a href="{{ url_for("auth.free_trial", plan="flex-v2") }}" class="sign-up btn btn-primary btn-lg">Start a free trial</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/main/templates/flex-panels/middle.html
<div class="middle">
    <div class="flex-panel">
        <div class="container">
            <div class="row">
                <div class="col-md-3 content-parent center hidden-xs hidden-sm">
                    <object data="/static/images/flex-landing/icon-savemoney@2x.svg" type="image/svg+xml" class="content"></object>
                </div>
                <div class="col-md-9 col-sm-12 content-parent card panel">
                    <div class="content">
                        <object data="/static/images/flex-landing/icon-savemoney@2x.svg" type="image/svg+xml" class="hidden-md hidden-lg"></object>
                        <h2>Save Money with Optimal Shifts</h2>
                        <p>
                            Over-scheduling wastes money. Under-scheduling delays fulfillment. Staffjoy's algorithms build schedules that precisely match your business's forecasted needs.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="flex-panel">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-12 content-parent card panel">
                    <div class="content">
                        <object data="/static/images/flex-landing/icon-oneclick@2x.svg" type="image/svg+xml" class="hidden-md hidden-lg"></object>
                        <h2>Claim Work In One Click</h2>
                        <p>
                            Staffjoy optimizes the contractor scheduling workflow: Open the app, see available shifts, then click to claim them.
                        </p>
                    </div>
                </div>
                <div class="col-md-3 content-parent center hidden-xs hidden-sm">
                    <object data="/static/images/flex-landing/icon-oneclick@2x.svg" type="image/svg+xml" class="content"></object>
                </div>
            </div>
        </div>
    </div>

    <div class="flex-panel">
        <div class="container">
            <div class="row">
                <div class="col-md-3 content-parent center hidden-xs hidden-sm">
                    <object data="/static/images/flex-landing/icon-scale@2x.svg" type="image/svg+xml" class="content"></object>
                </div>
                <div class="col-md-9 col-sm-12 content-parent card panel">
                    <div class="content">
                    <object data="/static/images/flex-landing/icon-scale@2x.svg" type="image/svg+xml" class="hidden-md hidden-lg"></object>
                        <h2>Scale Your Workforce</h2>
                        <p>
                            Manual operations do not scale. Staffjoy sets your scheduling to autopilot. As your workforce grows, the time it takes you to schedule stays the same. 
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

app/main/templates/flex-panels/overview.html
<div class="flex-panel cta" id="flex-overview">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 content-parent">
                <div class="content">
                    <h1>Marketplace Scheduling for Contractors</h1>

                    <p>Staffjoy calculates when you need shifts, then contractors claim the ones they want.</p>

                    <a href="{{ url_for("auth.free_trial", plan="flex-v2") }}" class="sign-up btn btn-primary btn-lg">Set up a {{ config.FREE_TRIAL_DAYS }} day trial</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/main/templates/flex.html
{% extends "bootstrap.html" %}

{% block page_id %}flex-landing{% endblock %}

{% block content %}
{% include "flex-panels/overview.html" %}
{% include "flex-panels/middle.html" %}
{% include "flex-panels/columns.html" %}
{% include "flex-panels/cta.html" %}
{% endblock %}

app/main/templates/homepage-panels/overview.html
<div class="homepage-panel" id="overview">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2 col-xs-12 content-parent">
                <div class="content">
                    <h1>{{config.DESCRIPTION}}</h1>

                    <p>{{config.DESCRIPTION_DETAIL}}</p>

                    <a href="{{ url_for("main.sign_up") }}" class="sign-up btn btn-primary btn-lg">Try It Now</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/main/templates/homepage-panels/panel-availability.html
<div class="homepage-panel" id="panel-availability">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-7 content-parent bottom-padding">
                <div class="content">
                    <h2>Choose when you want to work</h2>
                    <p>
                        Using the mobile-friendly Planner App, workers can set their availability to work, can see their scheduled shifts, and can claim open shifts.
                    </p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-5 content-parent center">
                <img src="/static/images/homepage/availability.png" alt="Workers set availability" class="content"/>
            </div>
        </div>
    </div>
</div>

app/main/templates/homepage-panels/panel-demand.html
<div class="homepage-panel" id="panel-demand">
    <div class="container">
        <div class="row">
            <div class="col-sm-5 content-parent center hidden-xs">
                <img src="/static/images/homepage/demand.png" alt="Workforce Demand" class="content"/>
            </div>
            <div class="col-sm-7 col-xs-12 content-parent">
                <div class="content">
                    <h2>Tell us when you need workers</h2>
                    <p>
                        Every week, choose the number of workers that you need, hour by hour, for each part of your business. Each worker has a customizable profile where you can set constraints, such as how many shifts they should work.
                    </p>
                </div>
            </div>
            <div class="col-xs-12 center visible-xs">
                <img src="/static/images/homepage/demand.png" alt="Workforce Demand" class="content"/>
            </div>
        </div>
    </div>
</div>

app/main/templates/homepage.html
{% extends "bootstrap.html" %}

{% block page_id %}homepage{% endblock %}

{% block content %}
<div class="panels">
    {% include "homepage-panels/overview.html" %}
    {% include "homepage-panels/panel-demand.html" %}
    {% include "homepage-panels/panel-availability.html" %}
    {% include "homepage-panels/panel-schedule.html" %}
</div>
{% endblock %}